version: '3.7'

volumes:
  postgres_data:
  static_value:
  media_value:
services:
  db:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  web:
    image: andyi95/yamdb_final
    restart: always
    volumes:
       - static_value:/code/static
       - media_value:/code/media
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    image: nginx:1.19.9-alpine
    restart: always
    ports:
    - 80:80
    volumes:
    - ./nginx/templates:/etc/nginx/templates
    - static_value:/var/html/static/
    - media_value:/var/html/media/
    env_file:
      - .env
    depends_on:
      - web
